### ISSUE TITLE
Tomcat location must be changed manually in struts-config.xml and web.xml 

### ISSUE THREAD

**Issue by gneissone** [OpenTopography/Opal-Toolkit#1]
I had to update Tomcat's port manually for files web.xml and struts-config.xml in Opal-Toolkit/webapps/opal2/WEB-INF/ since I'm running on a different port than 8080.

Can it be changed during build by reading tomcat.port from build.properties or tomcat.url from opal.properties? Or a reference to the files could be added to the installation instructions.

The error I received before changing struts-config.xml was:
2017-06-06 10:40:54,402 INFO  edu.sdsc.nbcr.opal.util.OpalDeployService$Deployer.run(OpalD
eployService.java:154) - Axis admin is not ready yet

**Comment by vnandigam** [comment]
Yes. catalina.home and tomcat.port should be set in build.properties before the build.

**Comment by gneissone** [comment]
I did set them in build.properties, but I still had to manually change the other files.

**Comment by vnandigam** [comment]
Are you using ant install? Can you let me know what version of ant/tomcat/OS?

**Comment by gneissone** [comment]
Sure, Ant version 1.9.6, Tomcat 8.5.6, OS X 10.11.6

**Comment by vnandigam** [comment]
Opal2 does not have support for Tomcat 8.x yet (Opal-Toolkit/CHANGELOG).

**Comment by gneissone** [comment]
Gotcha. FYI, as far as I can tell, Opal2 itself worked flawlessly on Tomcat 8.5.6 after changing the port in the two xml files.
